apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  namespace: kiratech-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: kiratech-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "{{ .Values.mysql.rootPassword }}"
        - name: MYSQL_DATABASE
          value: "{{ .Values.mysql.database }}"
        ports:
        - containerPort: 3306

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  namespace: kiratech-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: "{{ .Values.nodejs.image.repository }}:{{ .Values.nodejs.image.tag }}"
        ports:
        - containerPort: 3000