apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: kiratech-challenge
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: apache

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: kiratech-challenge
spec:
  type: {{ .Values.mysqlService.type }}
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql

---

apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: kiratech-challenge
spec:
  type: {{ .Values.nodejsService.type }}
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: nodejs
